language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - travis_retry composer install

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '8.0' ]; then
      - composer require --prefer-dist --no-interaction 'phpunit/phpunit:^9'
    fi


script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS